name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/docker@v2
    - name: Build the Docker image
      run: docker build . nilofe/go-server:v5:$(date +%s)
